sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: EXjCyN0jhFsUCGylDe+bBSZf7sTcn6sOoDfNpLSnaF7nF2L/IwbYMYYJtFD1wQaQH6uMe5rTRIZxH45bZaladG1U2iSQMXzJ0V+ELKYMUi8EA++gBB4sUYyXhrRXkx1R6PccJUUisXFjnrxdvhGgk6VZgp8XzxR8IBD7ufFKiQQaJf4kEng/mOwcyqCB4rsWwiqyUQ9U1OMwErNi/AR3snFyAgq2BXnIHB6LL3NPuUdbV/JPTEuCSpiX4A+sCMEz2LR2A/I9hTuQxaHj1NcEXBXmOLDWvhzkJba23yv9hTveUBAXquwGsyN1DTsZXnK/zRgDaeB3gHOSSB9vWuvCLfTHQpK1OdkcIuJhiy6cnrxBmM3FSGkx/CuKGmxrmqvlZqhulDLERuD1kZnulvYNx7Uc0ZJhBuC5yv47h3uRv5/uH8z+fjyY0IYwZgSvrW5AainTkPiAm5gwc0zkhH+a8GZE2k2vbDvwQwR6sN0n3qCn2+lC4pWhh+VUBLs+p2oiZ7ietbPynbkZAbTn76vVYm9sjGlB9mpSA0lPSJV2SOH9m7H+CEzoY3ks75lNfOTUaOiwfCvoTxvjn9AcgKIK0jHhik6QIgvw/gZSyPFqfzwnA4AxWr7TWygiSQYRpRPMwguWMHSshNSqNi3C76f1dnxxetsuuD7hmQZ4pL34r8Y=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Log-of-the--Jolly-Polly-_1808
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy